# Look at documentation for docker compose: 
# https://docs.docker.com/compose/compose-file/build

name: haxall-services
version: "1.0"

services:
  #main haxall application
  #using "build" looks for a local Dockerfile
  haxall:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: devrun
    ports: 8082:8082
    volumes:
      - haxall-database:/haxall/var
    depends_on: fantom
    cache_from:
      - type=local,src=haxallData/cache/haxall
    cache_to:
      - type=local,dest=haxallData/cache/haxall
    environment:
    args:

  #fantom container
  #using "image" pulls from GitHub Docker image registry
  fantom:
    image: "ghcr.io/fantom-lang/fantom:latest"
    cache_from:
      - type=local,src=haxallData/cache/fantom
    cache_to:
      - type=local,dest=haxallData/cache/fantom


# #by putting volumes here, I can define them and use them in multiple
# #of the above services. If the same volume is used in two services,
# #the data is shared, and both can modify it. 
# volumes:
#   haxall-database: