# look at fan/.github/workflows/publish.yaml as the base example
# what is the purpose of "name" ?
name: Build and Publish Docker image to GitHub Packages and Docker Hub

on:
  push: 
    branches: 
      - master
    tags:
      - v*

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-image:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      #what is an attestation?
      attestations: write

    steps:
      - name: Check out the repo
        #fantom uses v3, but the github docs uses v4. Is there a difference?
        uses: actions/checkout@v3

      - name: Log in to Docker Hub

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      # docker compose [-f <arg>...] [options] [COMMAND] [ARGS...]
      - name: Build Docker image with docker compose
        run: docker compose -f docker-compose.yml build --with-dependencies --pull

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}