# look at fan/.github/workflows/publish.yaml as the base example for this publish file
# Also look here: https://dev.to/ken_mwaura1/automate-docker-image-builds-and-push-to-github-registry-using-github-actions-4h20
name: Build and Publish Docker Image to GitHub Packages

on:
  push: 
    branches: 
      - main
      - docker
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  # This is equivalent to ${{ github.repository_owner }}/haxall
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      #what is an attestation?
      attestations: write

    # I don't know whether most of the below docker Github actions should be v1, v2, v3, v4, or main... I also don't know what those mean?
    # Maybe find some info here: https://docs.docker.com/build/ci/github-actions/
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # unsure if this bit here is neccessary, since we are using "docker compose build", not "docker compose up --build"
      - name: Remove and stop docker compose containers
        run: docker compose -f docker-compose.yml down

      # ABOUT THIS SECTION: https://stackoverflow.com/questions/53416685/docker-compose-tagging-and-pushing
      # ABOUT 2: https://forums.docker.com/t/docker-compose-push-multiple-services-containers-to-docker-hub/121826
      # - name: Build Docker image with docker compose
      #   # docker compose [-f <arg>...] [options] [COMMAND] [ARGS...]
      #   run: docker compose -f docker-compose.yml --progress=plain build --pull --no-cache --tag ${{ steps.meta.outputs.tags }} --label ${{ steps.meta.outputs.labels }}
        
      #About Docker bake: https://docs.docker.com/reference/cli/docker/buildx/bake/#set
      #Using github actions: https://github.com/docker/bake-action
      - name: Build Docker image with docker bake
        run: docker buildx bake -f docker-compose.yml --progress=plain --pull --no-cache --set haxall.tags="${{ steps.meta.outputs.tags }}" --set haxall.labels."${{ steps.meta.outputs.labels }}" haxall
      
      - name: Push Docker image
        run: docker push ${{ steps.meta.outputs.tags }}/docker:latest