name: Build and Publish Docker Image to GitHub Packages

# This workflow is run on any push to main, or when the push includes a version tag.
# Example: git push tag v1.0.0
on:
  push: 
    branches: 
      - main
      - '*'
    tags:
      - 'v*'
  # This enables a workflow to be triggered manually
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/haxall

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # tag with version number upon "git push tag"
            type=match,pattern=v(.*),group=1
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
 
      # About Docker buildx bake: https://docs.docker.com/reference/cli/docker/buildx/bake/
      # About Github Bake Action: https://github.com/docker/bake-action
      # The github 'docker/bake-action' doesn't allow for multiple tags/labels. They need to be done individually with --set options each...
      # But they can be done all at once with file outputs from the metadata step. 
      - name: Build & Push Docker image with Github Bake Action
        uses: docker/bake-action@v4
        with:
          source: '{{defaultContext}}:./' 
          push: true
          pull: true
          files: |
            ./docker-compose.yml
            ${{ steps.meta.outputs.bake-file-tags }}
            ${{ steps.meta.outputs.bake-file-labels }}
          targets: haxall